DATA SEGMENT
ASC DB 9,0,8 DUP(0)
;COUNT EQU $-ASC
CARRY1 DW 0
CARRY2 DW 0
CARRY3 DW 0
BIN DB 4 DUP(?)
OUTBUF DB 8 DUP(30),'$'
DATA ENDS
CODE    SEGMENT
		ASSUME CS:CODE,DS:DATA
START:  MOV AX,DATA
		MOV DS,AX
		LEA DX,ASC
		MOV AH,0AH
		INT 21H
		MOV DL,10
		MOV AH,2
		INT 21H
		LEA SI,ASC
		ADD SI,2
		LEA DI,BIN
		MOV BX,000AH
		XOR DX,DX
		XOR CX,CX
		MOV CL,[SI-1]
		SUB CL,1
		MOV AH,00H
		MOV AL,[SI]
		SUB AL,30H
LP1:	MUL BX
		ADD AL,[SI+01]
		SUB AL,30H
		INC SI
		MOV CARRY1,AX 
		MOV AX,CARRY2
		MOV CARRY3,DX
		MUL BX
		ADD AX,CARRY3
		MOV CARRY2,AX
		MOV AX,CARRY1
		LOOP LP1
		MOV DX,CARRY2
		MOV [DI],AX
        ADD DI,02H
		MOV [DI],DX
		MOV CX,4
		LEA DI,OUTBUF
		ADD DI,6
		LEA SI,BIN
LP2:    MOV AL,[SI]
		MOV AH,AL
		MOV BX,CX
		MOV CL,4
		ROR AL,CL
		MOV CX,BX
		AND AH,0FH
		AND AL,0FH
		ADD AL,30H
		CMP AL,39H
		JBE HEX1
		ADD AL,07H
HEX1:	ADD AH,30H
		CMP AH,39H
		JBE HEX2
		ADD AH,07H
HEX2:	MOV [DI],AX
		SUB DI,2
		INC SI
		LOOP LP2
		LEA DX,OUTBUF
		MOV AH,9
		INT 21H
		MOV AH,4CH
		INT 21H	
CODE ENDS
END START
